"""
API router for chatbot interactions.

Defines the RESTful endpoints.
This module acts as a "controller" connecting the HTTP layer to 
the chat service logic.
"""

from fastapi import APIRouter, Depends
from api.models.chat import ChatRequest, ChatResponse
from api.services.chat_service import get_chatbot_reply

router = APIRouter()

@router.post("/reply", response_model=ChatResponse)
async def chatbot_reply(request: ChatRequest):
    """
    POST endpoint to handle chatbot queries.

    Receives a user message, passes it to the chat service,
    and returns a response generated by the underlying LLM.

    Args:
        request (ChatRequest): Contains the user's input message.

    Returns:
        ChatResponse: The chatbot's generated reply.
    """
    return await get_chatbot_reply(request.message)
